# Set theme
remote_theme: lbulgarelli/personal-website

# Data
name: Lucas Bulgarelli
image: /assets/images/me.jpeg
position: Data Scientist & Engineer
email: lucas1@mit.edu
plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO tag
title: Lucas Bulgarelli
description: Data Scientist & Engineer
google_site_verification: aOpANQPhr4wfujF8HqSnPImTpgHuYREwR4yQ-pNvTBY
social:
  name: Lucas Bulgarelli
  links:
    - https://twitter.com/l_bulgarelli
    - https://www.facebook.com/bulgarelli.lucas
    - https://www.linkedin.com/in/lbulgarelli/
    - https://github.com/lbulgarelli
    - https://scholar.google.com/citations?user=vKfiYkcAAAAJ
    - https://www.instagram.com/bulgarelli_l/

# Defaults
defaults:
- scope:
    path: ""
  values:
    image:
      path: /assets/images/banner.jpg
      height: 1800
      width: 945